set -s set-clipboard on
set -g mouse on
set-option -g status-position top
set -g focus-events on
set -g allow-rename off
# Status configuration
set -g status-style bg=default
set -g status-left-length 99
set -g status-right-length 99
set -g status-justify centre

##### Keybinds #####
unbind t
unbind r
bind r source-file ~/.tmux.conf

bind -n M-Left select-pane -L 
bind -n M-Right select-pane -R 
bind -n M-Up select-pane -U   
bind -n M-Down select-pane -D

bind g display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "lazygit"
bind C-t display-popup \
  -w 80% \
  -h 80% \
  -E 'nvim ~/.tmux.conf'
bind C-n display-popup \
  -w 80% \
  -h 80% \
  -E 'nvim ~/.config/nvim'
bind a display-popup -d "#{pane_current_path}" -E "copilot"
bind t display-popup \
  -d "#{pane_current_path}" \
  -w 50% \
  -h 50% \
  -E "nu"
bind w display-popup -E "
  tmux list-windows -F '#I:#W' \
  | fzf --prompt='windows> ' \
  | awk -F: '{print \$1}' \
  | xargs -I{} tmux select-window -t {}
"

# Theme
# Catpucino
set -g @catppuccin_flavour "cyberdream"
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
