set -s set-clipboard on
set -g mouse on
set -g focus-events on
set -g allow-rename off
set -g default-terminal "tmux-256color"

##### Keybinds #####
unbind t
unbind r
bind r source-file ~/.tmux.conf

bind -n M-h select-pane -L 
bind -n M-l select-pane -R 
bind -n M-k select-pane -U   
bind -n M-j select-pane -D

bind g display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "lazygit"
bind C-t display-popup \
  -w 80% \
  -h 80% \
  -E 'nvim ~/.tmux.conf'
bind C-n display-popup \
  -w 80% \
  -h 80% \
  -E 'nvim ~/.config/nvim'
bind a display-popup -d "#{pane_current_path}" -E "copilot"
bind t display-popup \
  -d "#{pane_current_path}" \
  -w 50% \
  -h 50% \
  -E "nu"
bind w display-popup -E "
  tmux list-windows -F '#I:#W' \
  | fzf --prompt='windows> ' \
  | awk -F: '{print \$1}' \
  | xargs -I{} tmux select-window -t {}
"

# Theme
# Catpucino
set -g @catppuccin_flavour "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_status_background "default"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
# Status configuration
set-option -g status-position top
# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""

set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

run ~/.config/tmux/plugins/tmux-cpu/cpu.tmux
