# libinput-gestures configuration
# https://github.com/bulletmark/libinput-gestures

# 3-finger swipe left -> next workspace
gesture swipe left 3 swaymsg workspace next

# 3-finger swipe right -> previous workspace
gesture swipe right 3 swaymsg workspace prev
